### PR TITLE
adding ci/cd github actions pipeline

### LINKED ISSUE #1: Add macOS wheel + tar.gz (sdist) to PyPI
Easiest way would be to add CI for that. Would it be OK if I send a PR using azure pipelines? (`orjson` has good examples)

### LINKED ISSUE #20: Wheels for python 3.11
Hello,
can you please release wheels for python 3.11 since the release is in a few days?

Thanks a lot!

### PR DESCRIPTION
**Pull request by Grommash9**
Closes #1
Closes #20 

As I can see now there is no working pipeline really but it's would be great to have one

For using that you will need to generate and add your `PYPI_API_TOKEN` into repository settings

Please let me know if there is any issues with it  

In that pipeline we will run tests for any PR

And if there was an event of push + tag contains `.` it will tag it and push it to pypi

### CODE REVIEW

**Comment by Grommash9** [comment]
Maybe you also should something like `allow running actions for that repo` so check will start starting from that PR

**Comment by Grommash9** [comment]
Fore testing that I had created my own repo and run whole process, you can see how actions works here

https://github.com/Grommash9/test_fastuuid/actions/runs/10076792038

You can also see the result of it posted here:

https://pypi.org/project/test-fastuuid/

**Comment by Grommash9** [comment]
image

image

**Comment by thedrow** [comment]
@Grommash9 Would you like me to add you as a contributor to this repository and to PyPi so you can do it yourself?

**Comment by Grommash9** [comment]
@thedrow yes, I am happy to do that

**Comment by Grommash9** [comment]
It's a url to my pypi profile

https://pypi.org/user/prudnikov21/

**Comment by thedrow** [comment]
@Grommash9 I added you to this repository and to PyPi

**Review by thedrow — APPROVED** [review]

**Pull request merged**
