### PR TITLE
UUID can be subclassed (e.g. for typing.NewType). Add typing hints.

### LINKED ISSUE #21: Type hints
Hey,
would it be possible to add type hints to the package? They could mostly be copied from the stdlib (tyoeshed/stdlib). As an alternative thy could be added to typeshed/stubs.

What do you think?

### PR DESCRIPTION
**Pull request by enerqi**
Fixes #21 
- UUID class can be subclassed by python types
- move fields in package.metadata.maturin to where expected in pyproject.toml
- type hints for python tooling manually maintained in fastuuid.pyi

### CODE REVIEW

**Review by thedrow — APPROVED** [review]

**Comment by thedrow** [comment]
Thanks!

**Comment by kasium** [comment]
Not sure, but isn't a py.typed file missing?

**Comment by enerqi** [comment]
> 

"In a pure Rust project, add type stubs in a <module_name>.pyi file in the project root. Maturin will automatically include this file along with the required py.typed file for you."

https://github.com/PyO3/maturin/blob/main/guide/src/project_layout.md

**Comment by kasium** [comment]
Great!

**Pull request merged**
